"""Add analysis fields to Property model

Revision ID: ab7bde6fa664
Revises: b43eea443eb5
Create Date: 2026-01-02 15:08:16.579398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7bde6fa664'
down_revision: Union[str, None] = 'b43eea443eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create PropertyCondition ENUM type
    property_condition_enum = sa.Enum('NEW', 'BRAND_NEW', 'GOOD', 'TO_REFURBISH', 'UNDER_CONSTRUCTION', 'EXCELLENT', name='propertycondition')
    property_condition_enum.create(op.get_bind(), checkfirst=True)

    # Add PropertyStatus RESERVED value
    op.execute("ALTER TYPE propertystatus ADD VALUE IF NOT EXISTS 'reserved'")

    op.add_column('properties', sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('properties', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('street_number', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('property_condition', property_condition_enum, nullable=True))
    op.add_column('properties', sa.Column('observations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'observations')
    op.drop_column('properties', 'property_condition')
    op.drop_column('properties', 'street_number')
    op.drop_column('properties', 'street')
    op.drop_column('properties', 'estimated_value')
    # ### end Alembic commands ###
